# Generated by Django 5.1.5 on 2025-03-01 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_delete_workoutplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.AddField(
            model_name='workout',
            name='category',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
