# Generated by Django 5.1.5 on 2025-03-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_nutrition_remove_workout_duration_workout_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
