# Generated by Django 5.1.5 on 2025-03-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workout_duration_alter_workout_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='category',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
